### ISSUE TITLE
CRAN resurrection?

### ISSUE THREAD

**Issue by zeileis** [pradosj/bmrm#3]
Hi @pradosj, are there any plans to update the `bmrm` package so that it can be resurrected on [CRAN](https://CRAN.R-project.org/web/packages/bmrm/)? I'm asking because it was listed in the MachineLearning task view, see https://github.com/cran-task-views/MachineLearning/issues/13
Thanks in advance for your consideration!

**Comment by pradosj** [comment]
Dear Achim,

bmrm package depends on LowRankQP which is depreciated, and I cannot resurrect it without resurrection of LowRankQP.

An alternative to bmrm could be to use packages torch+luz

Best
Julien

**Comment by zeileis** [comment]
Thanks for the feedback, Julien, much appreciated.

If there are no alternative implementations for this on CRAN, I would recommend that you try to get in touch with the LowRankQP maintainer and/or consider resurrecting that package yourself.

For now I will remove bmrm from the task view. In case you do bring it back to CRAN, feel free to ping us to be reincluded in the task view.
